image: node:12.16.1
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
